openapi: 3.0.1
info:
  title: EXO-FIN-GPT API
  version: "1.0"
servers:
  - url: /
paths:
  /predict:
    post:
      summary: Ejecutar predicción ROI y Sharpe
  /evaluate:
    get:
      summary: Mostrar resultados simulados
  /risk:
    get:
      summary: Evaluar riesgo de inversión
  /health:
    get:
      summary: Verificar estado del sistema
