openapi: 3.0.1
info:
  title: EXO-FIN-GPT
  version: "1.0"
paths:
  /predict:
    post:
      summary: "Generar predicción reflexiva"
  /risk:
    get:
      summary: "Consultar riesgo del portafolio"
  /evaluate:
    get:
      summary: "Resultados del simulador"
  /health:
    get:
      summary: "Estado del sistema"

