openapi: 3.0.1
info:
  title: EXO-FIN-GPT API
  version: "1.0"
paths:
  /predict:
    post:
      summary: Ejecuta predicción con ROI y Sharpe
  /risk:
    get:
      summary: Perfil de riesgo del portafolio
  /evaluate:
    get:
      summary: Resultados de simulación
  /health:
    get:
      summary: Estado del sistema

