openapi: 3.0.1
info:
  title: EXO-FIN-GPT API
  version: "1.0"
paths:
  /predict:
    post:
      summary: Predicción con ROI y Sharpe
  /evaluate:
    get:
      summary: Resultado de la simulación
  /risk:
    get:
      summary: Evaluación del portafolio
  /health:
    get:
      summary: Estado del sistema

