openapi: 3.0.1
info:
  title: EXO-FIN-GPT API
  version: "1.0"
paths:
  /predict:
    post:
      summary: Ejecuta predicción con ROI y Sharpe
      description: Calcula las métricas financieras para la serie de precios proporcionada
  /explain/{ticker}:
    get:
      summary: Explica la decisión para un ticker
      parameters:
        - in: path
          name: ticker
          required: true
          schema:
            type: string
  /risk:
    get:
      summary: Perfil de riesgo del portafolio
  /evaluate:
    get:
      summary: Resultados de simulación
  /feedback:
    post:
      summary: Recibe feedback del usuario
      description: Almacena comentarios para refinar las decisiones futuras
  /health:
    get:
      summary: Estado del sistema

