openapi: 3.0.1
info:
  title: EXO-FIN-GPT
  version: "1.0"
paths:
  /predict:
    post:
      summary: "Predicción ROI y Sharpe"
  /risk:
    get:
      summary: "Evaluación de riesgo"
  /evaluate:
    get:
      summary: "Simulación actual"
  /health:
    get:
      summary: "Estado del sistema"

