openapi: 3.0.1
info:
  title: EXO-FIN-GPT API
  version: "1.0"
paths:
  /predict:
    post:
      summary: Ejecuta predicción con ROI y Sharpe
  /explain/{ticker}:
    get:
      summary: Explica el razonamiento para un ticker
  /evaluate:
    get:
      summary: Resultados de simulación
  /feedback:
    post:
      summary: Recibir retroalimentación del usuario
  /risk:
    get:
      summary: Riesgo del portafolio
  /health:
    get:
      summary: Estado del sistema

